export const CREATE_MESSAGEGROUP = 'CREATE_MESSAGEGROUP';
export const FETCH_MESSAGEGROUPS = 'FETCH_MESSAGEGROUPS';
export const FETCH_MESSAGEGROUP = 'FETCH_MESSAGEGROUP';
export const DELETE_MESSAGEGROUP = 'DELETE_MESSAGEGROUP';
export const EDIT_MESSAGEGROUP = 'EDIT_MESSAGEGROUP'